added a wrapper around the `entt::entity` type for easier usage, added demonstration code
mgerhold/silly-sprites pull request #41
Opened 2023-07-31 19:45 UTC by mgerhold

2023-08-01 16:34 UTC, PurpurTentakel97 requested changes

2023-08-01 16:34 UTC, PurpurTentakel97 commented on src/silly_sprites/entity.hpp
> +        friend std::ostream& operator<<(std::ostream& ostream, const Entity& entity) {
wrong const

2023-08-01 17:48 UTC, mgerhold commented on src/silly_sprites/entity.hpp
> +    public:
I opened a [discussion](https://github.com/mgerhold/silly-sprites/discussions/43) on that topic. Let's talk about it there :)

2023-08-01 17:52 UTC, mgerhold commented on src/silly_sprites/native_script.hpp
> +
Do you mean between `#pragma once` and the `#include`s? I prefer to put a newline there. Clang-format does not force this, though. Should we add this to the styleguide? Would you put the newline there or not?

2023-08-01 19:47 UTC, PurpurTentakel97 commented on src/silly_sprites/native_script.hpp
> +
i think i like it.
so lets add it to the styleguide

2023-08-04 16:07 UTC, PurpurTentakel97 approved these changes

2023-08-04 16:16 UTC, merged